-- =========================================
-- SKRIP SETUP TABEL GURU BIMBEL (TUTORING TEACHERS)
-- Silakan copy-paste script ini ke SQL Editor di Dashboard Supabase Anda
-- =========================================

-- 1. TABEL MATA PELAJARAN BIMBEL (Parent Table)
-- Tabel ini harus dibuat dulu karena tabel guru akan mereferensi ke id mapel ini.
CREATE TABLE IF NOT EXISTS public.tutoring_subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    classes TEXT[] DEFAULT '{}', -- Array text, contoh: {'1', '2', '3'}
    meetings_count INTEGER DEFAULT 12,
    status TEXT DEFAULT 'Aktif',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABEL GURU BIMBEL (FOKUS UTAMA)
-- Tabel ini menyimpan data login untuk Guru Bimbel
CREATE TABLE IF NOT EXISTS public.tutoring_teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    source TEXT DEFAULT 'Internal', -- 'Internal' atau 'Eksternal'
    subject_id INTEGER REFERENCES public.tutoring_subjects(id) ON DELETE SET NULL,
    subject_name TEXT, -- Disimpan redundant agar akses data lebih cepat (denormalization)
    class_id TEXT,     -- Contoh: 'Kelas 6', 'Group A'
    schedule_day TEXT, -- Contoh: 'Senin'
    schedule_start TEXT, -- Contoh: '14:00'
    schedule_end TEXT,   -- Contoh: '15:30'
    username TEXT UNIQUE NOT NULL, -- PENTING: Digunakan untuk Login
    password TEXT NOT NULL,        -- PENTING: Digunakan untuk Login
    students_count INTEGER DEFAULT 0,
    status TEXT DEFAULT 'Aktif',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ENABLE ROW LEVEL SECURITY (RLS)
-- Ini penting agar tabel aman tapi tetap bisa diakses sesuai policy
ALTER TABLE public.tutoring_subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tutoring_teachers ENABLE ROW LEVEL SECURITY;

-- 4. BUAT POLICY AKSES DATA (CRUD)
-- PENTING: "Public Read" diperlukan agar halaman Login bisa mengecek username/password

-- Hapus policy lama jika ada (untuk menghindari error duplikat saat run ulang)
DROP POLICY IF EXISTS "Public Read Access" ON public.tutoring_teachers;
DROP POLICY IF EXISTS "Public Write Access" ON public.tutoring_teachers;
DROP POLICY IF EXISTS "Public Read Access" ON public.tutoring_subjects;
DROP POLICY IF EXISTS "Public Write Access" ON public.tutoring_subjects;

-- Buat Policy Baru untuk Teachers
CREATE POLICY "Public Read Access" ON public.tutoring_teachers
FOR SELECT USING (true);

CREATE POLICY "Public Write Access" ON public.tutoring_teachers
FOR ALL USING (true); -- Mengizinkan Insert/Update/Delete

-- Buat Policy Baru untuk Subjects
CREATE POLICY "Public Read Access" ON public.tutoring_subjects
FOR SELECT USING (true);

CREATE POLICY "Public Write Access" ON public.tutoring_subjects
FOR ALL USING (true);

-- 5. CONTOH DATA DUMMY (Opsional)
-- Uncomment baris di bawah ini jika ingin langsung mengisi data contoh mapel dan guru

/*
INSERT INTO public.tutoring_subjects (name, classes, meetings_count)
VALUES ('Matematika Dasar', '{1,2,3}', 12);

INSERT INTO public.tutoring_teachers (name, subject_name, username, password, class_id)
VALUES ('Budi Santoso', 'Matematika Dasar', 'budi123', '123456', 'Kelas 1');
*/
